[package]
name = "litep2p-perf"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
clap = { version = "4.5.31", features = ["derive", "cargo"] }
tokio = { version = "1.28", features = ["macros", "time", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1.34"
futures = "0.3.28"

litep2p = { git = "https://github.com/ChainSafe/litep2p", rev = "78d0b6da78aaf9bae8af1f58d427bdd139f36521", features = ["websocket", "webrtc"] }

utils = { path = "../utils" }
